### ISSUE TITLE
Uploading problem: uploading stub...

### ISSUE THREAD

**Issue by jjviton** [xoseperez/espurna#1992]
Hi all,

I´ve just received a new TH10 and I would like to fash it with Espurna. But I get this error, at stub stage. (using same procedure I can flash POW perfectly) 
Any idea to fix it?

**_Serial port COM7
Connecting...
Detecting chip type... ESP8266
Chip is ESP8266EX
Features: WiFi
Crystal is 26MHz
MAC: cc:50:e3:ca:e2:c3
Uploading stub...
Running stub...
Traceback (most recent call last):
  File "esptool.py", line 3201, in <module>
    _main()
  File "esptool.py", line 3194, in _main
    main()
  File "esptool.py", line 2909, in main
    esp = esp.run_stub()
  File "esptool.py", line 637, in run_stub
    p = self.read()
  File "esptool.py", line 292, in read
    return next(self._slip_reader)
StopIteration_**

**Comment by jjviton** [comment]
command:
**python esptool.py --port COM7 --baud 9600 erase_flash
esptool.py v2.8**

**Comment by jjviton** [comment]
Hi again,
After two days, reading and testing I dicover that it is a power problem.

SONOFF TH10 pcb ver: 2.1. needs 5volt to be programmed!!!! (only 3,3v are not enought)

Another small step for a man...
