### ISSUE TITLE
Cannot set new password

### ISSUE THREAD

**Issue by MADSC-64** [xoseperez/espurna#2461]
After building and flashing espurna and connecting to the ap. It asked me to create a new password but anything I entered gave me:
`TypeError: Cannot read property 'elements' of undefined
    at http://192.168.4.1/:17:16672
    at Array.filter (<anonymous>)
    at validateFormPasswords (http://192.168.4.1/:17:16660)
    at sendPasswordConfig (http://192.168.4.1/:17:29319)
    at HTMLButtonElement.<anonymous> (http://192.168.4.1/:17:39231)

For more info see the Developer Tools console.`

And the developer console showed

`Error handling response: TypeError: Cannot read property 'encrypt' of undefined
    at Object.13 (chrome-extension://bkdgflcldnnnapblkhphbgpggdiikppg/public/js/content-scripts/autofill.js:1435:33)
    at o (chrome-extension://bkdgflcldnnnapblkhphbgpggdiikppg/public/js/content-scripts/autofill.js:1:265)
    at chrome-extension://bkdgflcldnnnapblkhphbgpggdiikppg/public/js/content-scripts/autofill.js:1:316
    at Object.12../captureDdgGlobals (chrome-extension://bkdgflcldnnnapblkhphbgpggdiikppg/public/js/content-scripts/autofill.js:1319:20)
    at o (chrome-extension://bkdgflcldnnnapblkhphbgpggdiikppg/public/js/content-scripts/autofill.js:1:265)
    at chrome-extension://bkdgflcldnnnapblkhphbgpggdiikppg/public/js/content-scripts/autofill.js:1:316
    at Object.1../UI/CredentialsAutofill (chrome-extension://bkdgflcldnnnapblkhphbgpggdiikppg/public/js/content-scripts/autofill.js:32:5)
    at o (chrome-extension://bkdgflcldnnnapblkhphbgpggdiikppg/public/js/content-scripts/autofill.js:1:265)
    at chrome-extension://bkdgflcldnnnapblkhphbgpggdiikppg/public/js/content-scripts/autofill.js:1:316
    at inject (chrome-extension://bkdgflcldnnnapblkhphbgpggdiikppg/public/js/content-scripts/autofill.js:1646:29)

Uncaught TypeError: Cannot read property 'elements' of undefined
    at (index):17
    at Array.filter (<anonymous>)
    at validateFormPasswords ((index):17)
    at sendPasswordConfig ((index):17)
    at HTMLButtonElement.<anonymous> ((index):17)`

I tried finding other issue reports that had the same problem but all of them are out of date and their solutions did not work

**Comment by mcspr** [comment]
> I tried finding other issue reports that had the same problem but all of them are out of date and their solutions did not work

In case this *might* happen again, there is always the following js (...or, at least until the configuration API remains the same):
```js
sendConfig({adminPass:["abcdefgh","abcdefgh"]})
```

Should be fixed by the commit.
